package MachineLearning;
/*
The purpose of this program is to help the web crawler to find the good type of each component
 */

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/*
Read a file generated by the web crawler and finds all non typed components
there are 3 files, Vegetables and raw materials, meat fish cheese, modifier
The file modifier contains all modifiers for meat cheese fish, like grated or chopped
 */
public class RecipeeReader {

    private List<String> meatFishCheeseList;
    private List<String> modifiers;
    private List<String> vegetables;


    public RecipeeReader(String meatFishCheese, String modifiers, String vegetables){
        this.meatFishCheeseList=makeList(meatFishCheese);
        this.modifiers=makeList(modifiers);
        this.vegetables=makeList(vegetables);
        System.out.println(this.vegetables);
    }

    private List<String> makeList(String fileName){0
        Stream<String> stream = null;
        List<String> list = null;
        try {
            stream = Files.lines(Paths.get(fileName));
        } catch (IOException e) {
            e.printStackTrace();
        }

        list = stream.map(String::toUpperCase)
                .collect(Collectors.toList());

        return list;
    }

    public static void main(String[] args){
        RecipeeReader r = new RecipeeReader("/home/kwidz/Cours/Memoire Maitrise/ExtracteurIngrédients/src/MachineLearning/Meat.txt","/home/kwidz/Cours/Memoire Maitrise/ExtracteurIngrédients/src/MachineLearning/Modifiers.txt", "/home/kwidz/Cours/Memoire Maitrise/ExtracteurIngrédients/src/MachineLearning/Vegetables.txt");
    }

}
