package ExtracteurIngredients;

import java.util.ArrayList;
import java.util.Arrays;

public class Main {

    public static void main(String[] args) {

        ArrayList<String> FruitsEtLegumes = new ArrayList<String>(Arrays.asList("Abricot",
                "Ail",
                "Airelle",
                "Amande",
                "Ananas",
                "Artichaut",
                "Asperge blanche",
                "Asperge verte",
                "Aubergine",
                "Avocat",
                "Banane",
                "Bette",
                "Betterave rouge",
                "Brocoli",
                "Carotte",
                "Cassis",
                "Catalonia",
                "Céleri",
                "Céleri branche",
                "Céleri rave",
                "Cerise",
                "Châtaigne",
                "Chou blanc",
                "Chou de Bruxelles",
                "Chou frisé",
                "Chou Romanesco",
                "Chou rouge",
                "Chou-chinois",
                "Chou-fleur",
                "Chou-rave",
                "Cima di Rapa",
                "Citron",
                "Citrouille",
                "Clémentine",
                "Coing",
                "Concombre",
                "Courge",
                "Courgette",
                "Cresson",
                "Datte",
                "Endive",
                "Epinard",
                "Fenouil",
                "Figue fraîche",
                "Fraise",
                "Fraise des bois",
                "Framboise",
                "Fruit de la passion",
                "Grenade",
                "Groseille",
                "Groseille à maquereau",
                "Haricot",
                "Kaki",
                "Kiwi",
                "Kumquat",
                "Laitue romaine",
                "Litchi",
                "Mâche",
                "Maïs",
                "Mandarine",
                "Mangue",
                "Marron",
                "Melon",
                "Menthe",
                "Mirabelle",
                "Mûre",
                "Myrtille",
                "Navet",
                "Nectarine",
                "Noisette",
                "Noix",
                "Oignon",
                "Orange",
                "Orange sanguine",
                "Pamplemousse",
                "Panais",
                "Papaye",
                "Pastèque",
                "Patate",
                "Pâtisson",
                "Pêche",
                "Petit oignon blanc",
                "Petit pois",
                "Poire",
                "Poireau",
                "Pois",
                "Poivron",
                "Pomme",
                "Pomme de terre",
                "Potimarron",
                "Potiron",
                "Prune",
                "Quetsche",
                "Radis",
                "Radis long",
                "Raisin",
                "Reine-claude",
                "Rhubarbe",
                "Salsifis",
                "Tomate",
                "Tomate charnue",
                "Tomate Peretti",
                "Topinambour"));

        Trie trie = new Trie(false);
        for (String item:FruitsEtLegumes
             ) {
            trie.insert(item);
        }

	 IGACrawler i = new IGACrawler(trie);
    }
}
